name: CI

on:
  push:
    branches: [master, nonprod, dev]

jobs:
  build-test-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Validate SAM template
        run: sam validate --lint --template-file stacks/root.yaml

      - name: Build SAM
        run: sam build --use-container --template-file stacks/root.yaml
