name: Infrastructure Deployment

on:
  push:
    branches:
      - dev
      - nonprod
      - master
      - feat/step-fn
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to DEV
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/feat/step-fn') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Deploy to DEV
        run: |
          STACK_NAME="bancow-dev-infra"
          DEPLOY_BUCKET="bancow-dev-sam-deployment"
          
          sam build --template-file stacks/root.yaml
          
          sam deploy \
          --stack-name $STACK_NAME \
          --s3-bucket $DEPLOY_BUCKET \
          --config-file samconfig.toml \
          --config-env dev \
          --no-fail-on-empty-changeset \
          --on-failure DO_NOTHING \
          --role-arn ${{ secrets.CFN_EXECUTION_ROLE_ARN }} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
          --parameter-overrides $(jq -r '.Parameters | to_entries | map("\(.key)=\(.value)") | join(" ")' environments/dev/parameters.json)

  deploy-uat:
    name: Deploy to UAT
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/nonprod') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'uat')
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Deploy to UAT
        run: |
          jq -r '.Parameters | to_entries | map("\(.key)=\(.value)") | join(" ")' environments/uat/parameters.json > params_uat.txt
          sam deploy \
          --config-file samconfig.toml \
          --config-env uat \
          --template-file stacks/root.yaml \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --role-arn ${{ secrets.CFN_EXECUTION_ROLE_ARN }} \
          --parameter-overrides $(cat params_uat.txt)

  deploy-prod:
    name: Deploy to PROD
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Deploy to PROD
        run: |
          jq -r '.Parameters | to_entries | map("\(.key)=\(.value)") | join(" ")' environments/prod/parameters.json > params_prod.txt         
          sam deploy \
          --config-file samconfig.toml \
          --config-env prod \
          --template-file stacks/root.yaml \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --role-arn ${{ secrets.CFN_EXECUTION_ROLE_ARN }} \
          --parameter-overrides $(cat params_prod.txt)
  notify:
    name: Notify deployment status
    needs: [ deploy-dev, deploy-uat, deploy-prod ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: echo "Deployment process finished."